---
- name: Create Security Group
  local_action:
    module: ec2_group
    name: "{{ security_group }}"
    description: Giropops Security Group
    region: "{{ region }}"
    profile: "{{ profile }}"
    rules:
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: 0.0.0.0/0
    rules_egress:
    - proto: all
      cidr_ip: 0.0.0.0/0
  register: basic_firewall

- name: Create EC2 instance
  local_action: ec2
    group={{ security_group }}
    instance_type={{ instance_type }}
    image={{ image }}
    profile="{{ profile }}"
    wait=true
    region={{ region }}
    keypair={{ keypair }}
    count={{ count }}
  register: ec2

- name: Add instance into temporary inventory
  add_hosts: name={{ item.public_ip }} groups=giropops-new
  with_items: "{{ ec2.instances }}"

- name: Add created instances on hosts file
  local_action: lineinfile
    dest="./hosts"
    regexp={{ item.public_ip }}
    insertafter="[kubernetes]" line={{ item.public_ip }}
  with_items: "{{ ec2.instances }}"

- name: SSH wait
  local_action: wait_for
    host={{ item.public_ip }}
    port=22
    state=started
  with_items: "{{ ec2.instances }}"

- name: Add tag name into instance
  local_action: ec2_tag resource={{ item.id }} region={{ region }}  profile={{ profile }} state=present
  with_items: "{{ ec2. instances }}"
  args:
    tags:
      Name: ansible-day2

- name: Add the newly created EC2 into know_hosts
  shell: ssh-keyscan -H {{ item.public_ip }} >> ~/.ssh/know_hosts
  with_items: "{{ ec2.instances }}"