---
- name: Configure Nginx
  hosts: webservers

  tasks:
    - name: Nginx setup
      apt:
        name: nginx
        state: latest
        update_cache: yes
    
    - name: Starting Nginx
      service:
        name: nginx
        state: started

    - name: Copy personalized index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html
