# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "node-03"
  config.vm.network "private_network", ip: "192.168.2.13"
  # config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.provision "shell", path: "provision.sh"

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end
end
