---
- hosts: all
  become: true
  user: vagrant
  gather_facts: no
  pre_tasks:
  - name: 'Python installation'
    raw: 'apt-get -y install python'
  roles:
  - install-k8s

- hosts: k8s-master
  become: true
  user: vagrant
  roles:
  - create-cluster

- hosts: k8s-workers
  become: true
  user: vagrant
  roles:
  - join-workers

- hosts: k8s-master
  become: true
  user: vagrant
  roles:
  - install-helm